version: "3.8"

networks:
  starter-network:
    name: starter-network

services:
  backend:
    container_name: starter-backend
    image: "node:12.13-alpine"
    command: sh -c "yarn && yarn start:dev"
    restart: on-failure
    volumes:
      - "./backend/package.json:/usr/app/package.json"
      - "./backend/yarn.lock:/usr/app/yarn.lock"
      - "./backend/nest-cli.json:/usr/app/nest-cli.json"
      - "./backend/tsconfig.json:/usr/app/tsconfig.json"
      - "./backend/tsconfig.build.json:/usr/app/tsconfig.build.json"
      - "./backend/src:/usr/app/src"
      - "backend_node_modules:/usr/app/node_modules"
    working_dir: /usr/app
    ports:
      - "${BACKEND_PORT:-4000}:4000"
      - "${DEBUGGER_PORT:-9229}:9229"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - starter-network

  db:
    container_name: starter-db
    image: mongo:4.4.0-bionic
    restart: on-failure
    env_file:
      - .env
    networks:
      - starter-network
    ports:
      - "${MONGO_PORT:-5000}:5000"

volumes:
  backend_node_modules:
